### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by xoste49** [glmn/wb-private-api#10]
![2022-11-24_123600](https://user-images.githubusercontent.com/7299412/203749449-462d79c5-6b3c-4985-9fef-5897b94eff56.png)
![2022-11-24_123609](https://user-images.githubusercontent.com/7299412/203749455-60ffe189-d814-498c-aa9c-7c261b6bbe09.png)
![2022-11-24_123649](https://user-images.githubusercontent.com/7299412/203749458-ec6669b7-f65a-4447-ba5c-e727db9428ca.png)

**Comment by glmn** [comment]
Исправлено в 680d118d15110179fc74285babc05515b21b4f0a
![Screenshot 2022-11-25 190136](https://user-images.githubusercontent.com/1326151/204022153-676d502a-be72-4977-a0d2-221d3ba05a9d.png)
