### ISSUE TITLE
Как запустить тесты?

### ISSUE THREAD

**Issue by ChangeNick** [glmn/wb-private-api#39]
Здравствуйте, сабж в названии.
И ещё один вопрос, вб заблокировал запросы, можно как-то прикрутить использование прокси?

**Comment by glmn** [comment]
```
> git clone https://github.com/glmn/wb-private-api.git
> cd wb-private-api
> npm install
> jest --verbose
```

Proxy можно прикрутить в SessionBuilder

```js
proxy: {
  protocol: 'http',
  host: '149.129.239.170',
  port: 8080
}
```
![image](https://github.com/glmn/wb-private-api/assets/1326151/44b39169-f66c-4916-af0f-d5b22ed52fb6)

Буду рад увидеть PR на добавление прокси ;)
