### ISSUE TITLE
 FAIL  tests/WBPrivateAPI.test.js

### ISSUE THREAD

**Issue by carden-code** [glmn/wb-private-api#51]
> wb-private-api@0.6.3 test
> jest --verbose

 PASS  tests/Utils.test.js
  Проверка утилит Card
    ✓ Проверка генерации URL на логотип бренда Brand.imageURL() (3 ms)
    ✓ Проверка генерации URL на фотографии карточек Card.imageURL() (1 ms)
    ✓ Проверка метода getBasketNumber() генерации Basket номера по Артикулу товара (10 ms)

 PASS  tests/SessionBuilder.test.js
  Проверка класса SessionBuilder
    ✓ Проверка статичного метода .create() (4 ms)

 PASS  tests/WBCatalog.test.js
  Проверка класса WBCatalog
    ✓ Проверка метода .page() по ключевому запросу "Очки женские" (874 ms)
    ✓ Проверка метода .getPosition() по ключевому запросу "Менструальные чаши" (290 ms)
    ✓ Проверка метода .getPosition() на ответ при ложном поиске (507 ms)

 PASS  tests/WBProduct.test.js
  Проверка класса WBProduct
    ✓ Проверка метода .getStocks() на возврат данных об остатках товара на складах (627 ms)
    ✓ Проверка метода .getPromo() на возврат данных об участии в промо-акции (425 ms)
    ✓ Проверка метода .getFeedbacks() на возврат всех отзывов (919 ms)
    ✓ Проверка метода .getQuestions() на возврат всех вопросов (717 ms)

  console.log
    {
      name: 'Платье',
      catalog_type: 'preset',
      catalog_value: 'preset=500060403',
      normquery: 'платье',
      context_metadata: {},
      products: [
        {
          time1: 4,
          time2: 34,
          dist: 122,
          id: 149647710,
          root: 126758860,
          kindId: 2,
          brand: '365.SOWELL',
          brandId: 429535,
          siteBrandId: 439535,
          colors: [Array],
          subjectId: 69,
          subjectParentId: 1,
          name: 'Платье вечернее',
          supplier: 'ИП Пучков Максим Сергеевич',
          supplierId: 1145527,
          supplierRating: 4.5,
          priceU: 370000,
          salePriceU: 149800,
          sale: 59,
          logisticsCost: 0,
          returnCost: 0,
          diffPrice: false,
          saleConditions: 0,
          pics: 29,
          rating: 4,
          reviewRating: 4.4,
          feedbacks: 1332,
          volume: 11,
          viewFlags: 0,
          sizes: [Array],
          log: [Object]
        }
      ]
    }

      at Object.log (tests/WBPrivateAPI.test.js:50:13)

 FAIL  tests/WBPrivateAPI.test.js (9.105 s)
  Проверка поиска рекламодателей
    ✓ Проверка рекламы по Поиску .getSearchAds() (419 ms)
    ✓ Проверка карусели внутри карточки .getCarouselAds() (277 ms)
  Проверка поиска товаров WBPrivateAPI.search()
    ✓ Поиск количества товаров по ключевому запросу "Платье" (1282 ms)
    ✓ Поиск количества товаров (редких) по ключевому запросу "тату чебурашка" (107 ms)
    ✓ Поиск данных из фильтров по ключевому запросу "конструктор детский" (402 ms)
    ✕ Проверка получения Query Params по ключевому запросу "Платье" (285 ms)
    ✓ Проверка метода getQueryMetadata на запросы разных страниц (447 ms)
    ✓ Сбор 3 страниц товаров по ключевому запросу "Платье" (647 ms)
    ✓ Проверка фильтрации товаров по бренду и ключевому запросу "торшер" (180 ms)
    ✓ Проверка фильтрации товаров по поставщику и ключевому запросу "торшер" (182 ms)
    ✓ Проверка фильтрации товаров по бренду и по поставщику с ключевым запросом "торшер" (173 ms)
    ✓ Проверка совместимости с axios-retry (1650 ms)
    ✓ Проверка метода .getQueryMetadata на прохождение HTTP 429 ошибки (1383 ms)
    ✓ Проверка аргумента pageCount на понижение кол-ва страниц, если их меньше чем запрошено (202 ms)
    ✓ Проверка метода .keyHint(query) на вывод предположений по ключевому запросу "Платье" (59 ms)
    ✓ Проверка метода .searchSimilarByNm(productId) на возврат идентификаторов похожиш товаров (305 ms)
    ✓ Проверка метода .getPromos() на возврат текущих промо-акций (172 ms)
    ✓ Проверка метода .getListOfProducts() на возврат найденных товаров (249 ms)
  Проверка выдачи данных по продавцу
    ✓ Проверка метода .getSupplierInfo() (42 ms)

  ● Проверка поиска товаров WBPrivateAPI.search() › Проверка получения Query Params по ключевому запросу "Платье"

    expect(received).toBe(expected) // Object.is equality

    Expected: "subject"
    Received: "preset"

      50 |     console.log(metadata)
      51 |     expect(typeof metadata === "object").toBeTruthy();
    > 52 |     expect(catalog_type).toBe("subject");
         |                          ^
      53 |     expect(catalog_value).toBe("subject=69;70;2905;4000;4855;4857");
      54 |   });
      55 |

      at Object.toBe (tests/WBPrivateAPI.test.js:52:26)

Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 29 passed, 30 total
Snapshots:   0 total
Time:        9.412 s, estimated 41 s
Ran all test suites.

**Comment by glmn** [comment]
Исправлено в `0.6.4`
